// <auto-generated />
using System;
using Biblioteca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaDBContext))]
    [Migration("20200614180224_Biblioteca")]
    partial class Biblioteca
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Biblioteca.Models.Carti", b =>
                {
                    b.Property<int>("IdCarte")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor");

                    b.Property<string>("Cod")
                        .IsRequired();

                    b.Property<string>("Editura");

                    b.Property<string>("Titlu")
                        .IsRequired();

                    b.HasKey("IdCarte");

                    b.ToTable("Carti");
                });

            modelBuilder.Entity("Biblioteca.Models.Clienti", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .IsRequired();

                    b.Property<string>("Contact")
                        .IsRequired();

                    b.Property<string>("Nume")
                        .IsRequired();

                    b.HasKey("IdClient");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Biblioteca.Models.ImprumuturiCarti", b =>
                {
                    b.Property<int>("IdImprumut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataImprumut");

                    b.Property<DateTime?>("DataReturnare");

                    b.Property<int>("IdCarte");

                    b.Property<int>("IdClient");

                    b.HasKey("IdImprumut");

                    b.HasIndex("IdCarte");

                    b.HasIndex("IdClient");

                    b.ToTable("ImprumuturiCarti");
                });

            modelBuilder.Entity("Biblioteca.Models.ImprumuturiCarti", b =>
                {
                    b.HasOne("Biblioteca.Models.Carti", "Carti")
                        .WithMany("ImprumuturiCarti")
                        .HasForeignKey("IdCarte")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Biblioteca.Models.Clienti", "Clienti")
                        .WithMany("ImprumuturiCarti")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
