//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ImprumuturiCarti
    {
        public int IdImprumut { get; set; }

        [Required]
        [Display(Name = "Carte")]
        public int IdCarte { get; set; }

        [Required]
        [Display(Name = "Client")]
        public int IdClient { get; set; }

        [Display(Name = "Data imprumut")]
        public System.DateTime DataImprumut { get; set; }

        [Display(Name = "Data returnare")]
        public Nullable<System.DateTime> DataReturnare { get; set; }
    
        public virtual Carti Carti { get; set; }
        public virtual Clienti Clienti { get; set; }
    }
}
